<a href="https://colab.research.google.com/github/kailashchaudhary-p/Data-Science-Learning/blob/main/IPL_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
''' Project ka main goal kya hai?

Indian Premier League (IPL) ke historical data ko analyze karke yeh samajhna:

Kaun best players hain
Kaunsi teams consistent hain
Match jeetne ke patterns kya hain

Matlab: data se story nikalna'''

' Project ka main goal kya hai?\n\nIndian Premier League (IPL) ke historical data ko analyze karke yeh samajhna:\n\nKaun best players hain\nKaunsi teams consistent hain\nMatch jeetne ke patterns kya hain\n\nMatlab: data se story nikalna'

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
from google.colab import files
uploaded = files.upload()
matches = pd.read_csv("matches.csv")
deliveries = pd.read_csv("ipl_2022_deliveries (1).csv")
deliveries2= pd.read_csv("ipl_2023_deliveries.csv")
deliveries3= pd.read_csv("ipl_2023_deliveries.csv")
deliveries4= pd.read_csv("ipl_2024_deliveries.csv")
deliveries5= pd.read_csv("ipl_2025_deliveries.csv")
deliveries6= pd.read_csv("ipl_2026_deliveries.csv")

Saving ipl_2022_deliveries.csv to ipl_2022_deliveries (1).csv
Saving ipl_2023_deliveries.csv to ipl_2023_deliveries (1).csv
Saving ipl_2024_deliveries.csv to ipl_2024_deliveries (1).csv
Saving ipl_2025_deliveries.csv to ipl_2025_deliveries (1).csv
Saving ipl_2026_deliveries.csv to ipl_2026_deliveries (1).csv
Saving matches.csv to matches (1).csv

In [5]:
matches.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,5/4/2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,6/4/2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,7/4/2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,8/4/2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,8/4/2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [6]:
matches.isnull().sum()

id                   0
season               0
city                 7
date                 0
team1                0
team2                0
toss_winner          0
toss_decision        0
result               0
dl_applied           0
winner               3
win_by_runs          0
win_by_wickets       0
player_of_match      3
venue                0
umpire1              1
umpire2              1
umpire3            636
dtype: int64

In [7]:
deliveries.head()

,match_id,season,match_no,date,venue,batting_team,bowling_team,innings,over,striker,bowler,runs_of_bat,extras,wide,legbyes,byes,noballs,wicket_type,player_dismissed,fielder
0,202201,2022,1,"Mar 26, 2022","Wankhede Stadium, Mumbai",CSK,KKR,1,0.1,Gaikwad,Umesh Yadav,0,1,0,0,0,1,NaN,NaN,NaN
1,202201,2022,1,"Mar 26, 2022","Wankhede Stadium, Mumbai",CSK,KKR,1,0.1,Gaikwad,Umesh Yadav,0,0,0,0,0,0,NaN,NaN,NaN
2,202201,2022,1,"Mar 26, 2022","Wankhede Stadium, Mumbai",CSK,KKR,1,0.2,Gaikwad,Umesh Yadav,0,1,1,0,0,0,NaN,NaN,NaN
3,202201,2022,1,"Mar 26, 2022","Wankhede Stadium, Mumbai",CSK,KKR,1,0.2,Gaikwad,Umesh Yadav,0,0,0,0,0,0,NaN,NaN,NaN
4,202201,2022,1,"Mar 26, 2022","Wankhede Stadium, Mumbai",CSK,KKR,1,0.3,Gaikwad,Umesh Yadav,0,0,0,0,0,0,caught,Gaikwad,Nitish Rana

In [10]:
matches = matches.dropna()

In [11]:
top_batsman = deliveries.groupby('batsman')['batsman_runs'].sum().sort_values(ascending=False).head(10)

print(top_batsman)

KeyError: 'batsman'