In [1]:
import pandas as pd
import numpy as np

In [2]:
dec1={
    "name":['ram','rohan','kailash','kuljeet'],
    "marks":[45,65,67,78],
    "city":['kolkata','mukerian','gurdaspur','jammu']
}

In [3]:
df=pd.DataFrame(dec1)

In [4]:
df

      name  marks       city
0      ram     45    kolkata
1    rohan     65   mukerian
2  kailash     67  gurdaspur
3  kuljeet     78      jammu

In [8]:
df.to_csv('student_marks.csv',index=False)

In [12]:
newdf = pd.DataFrame(
    np.random.rand(334, 5),
    index=range(334)
)

In [13]:
newdf

            0         1         2         3         4
0    0.854216  0.478375  0.210953  0.049168  0.965204
1    0.536240  0.607333  0.732370  0.531973  0.702488
2    0.698151  0.962487  0.387326  0.413525  0.328023
3    0.868059  0.258802  0.194766  0.391194  0.937382
4    0.372462  0.344674  0.054060  0.094850  0.895711
..        ...       ...       ...       ...       ...
329  0.829128  0.109141  0.499819  0.954094  0.483476
330  0.545881  0.424489  0.825918  0.114806  0.068219
331  0.055985  0.472600  0.928114  0.129674  0.174889
332  0.280728  0.398912  0.572572  0.743642  0.230427
333  0.787266  0.252767  0.101936  0.623976  0.188324

[334 rows x 5 columns]

In [5]:
import numpy as np
import pandas as pd
ndf= pd.DataFrame(np.random.rand(500,54),index=range(500))

In [6]:
ndf

,0,1,2,3,4,5,6,7,8,9,...,44,45,46,47,48,49,50,51,52,53
0,0.646127,0.421830,0.300937,0.221519,0.591082,0.827469,0.335328,0.121879,0.702944,0.833093,...,0.810541,0.156537,0.974522,0.381415,0.893062,0.153853,0.976149,0.280890,0.526019,0.590742
1,0.516166,0.336969,0.301992,0.898601,0.766480,0.483937,0.449230,0.061990,0.849109,0.193729,...,0.475588,0.690407,0.245072,0.596123,0.080604,0.799867,0.674343,0.409952,0.043486,0.058778
2,0.882717,0.055703,0.403638,0.120454,0.789180,0.174387,0.875059,0.070752,0.650932,0.979102,...,0.312036,0.071406,0.580832,0.451012,0.208433,0.815638,0.973422,0.378349,0.928546,0.115266
3,0.790237,0.631604,0.365001,0.310088,0.156526,0.848137,0.377790,0.983210,0.530090,0.760130,...,0.571708,0.577000,0.374929,0.177354,0.454226,0.113463,0.183360,0.971156,0.198071,0.917636
4,0.262317,0.922413,0.302756,0.345134,0.541654,0.118747,0.449882,0.458496,0.856421,0.044601,...,0.379971,0.298777,0.322450,0.082879,0.397091,0.137521,0.358286,0.922888,0.941334,0.714008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,0.095077,0.818587,0.730545,0.447512,0.859875,0.050473,0.703909,0.550599,0.618244,0.037471,...,0.718554,0.857814,0.900487,0.013053,0.470947,0.389488,0.341577,0.730975,0.982431,0.112026
496,0.670837,0.681695,0.797778,0.565109,0.910833,0.923667,0.029773,0.803410,0.446913,0.741829,...,0.324716,0.224352,0.006119,0.028399,0.029362,0.461942,0.600152,0.633262,0.225479,0.572302
497,0.973067,0.067417,0.799066,0.645336,0.166415,0.788492,0.537863,0.604847,0.567573,0.292959,...,0.986105,0.549226,0.186319,0.927120,0.731376,0.987003,0.380554,0.735333,0.121523,0.490660
498,0.718090,0.851512,0.215108,0.025832,0.621196,0.514867,0.527410,0.734987,0.236629,0.807455,...,0.317893,0.870942,0.644679,0.131700,0.941714,0.257655,0.481981,0.006952,0.371291,0.555307
499,0.724859,0.878535,0.173302,0.075152,0.475569,0.896615,0.016339,0.326232,0.112709,0.080926,...,0.600367,0.068547,0.308158,0.320335,0.774146,0.860329,0.785939,0.073281,0.621955,0.715215