In [1]:
import numpy as np
import pandas as pd

In [2]:
dec1={
    "name":['ram','rohan','kailash','kuljeet'],
    "marks":[45,65,67,78],
    "city":['kolkata','mukerian','gurdaspur','jammu']
}

In [3]:
df=pd.DataFrame(dec1)

In [4]:
df

      name  marks       city
0      ram     45    kolkata
1    rohan     65   mukerian
2  kailash     67  gurdaspur
3  kuljeet     78      jammu

In [8]:
df.to_csv('student_marks.csv',index=False)

In [12]:
newdf = pd.DataFrame(
    np.random.rand(334, 5),
    index=range(334)
)

In [13]:
newdf

            0         1         2         3         4
0    0.854216  0.478375  0.210953  0.049168  0.965204
1    0.536240  0.607333  0.732370  0.531973  0.702488
2    0.698151  0.962487  0.387326  0.413525  0.328023
3    0.868059  0.258802  0.194766  0.391194  0.937382
4    0.372462  0.344674  0.054060  0.094850  0.895711
..        ...       ...       ...       ...       ...
329  0.829128  0.109141  0.499819  0.954094  0.483476
330  0.545881  0.424489  0.825918  0.114806  0.068219
331  0.055985  0.472600  0.928114  0.129674  0.174889
332  0.280728  0.398912  0.572572  0.743642  0.230427
333  0.787266  0.252767  0.101936  0.623976  0.188324

[334 rows x 5 columns]