In [1]:
import pandas as pd
import numpy as np

In [2]:
dec1={
    "name":['ram','rohan','kailash','kuljeet'],
    "marks":[45,65,67,78],
    "city":['kolkata','mukerian','gurdaspur','jammu']
}

In [3]:
df=pd.DataFrame(dec1)

In [4]:
df

      name  marks       city
0      ram     45    kolkata
1    rohan     65   mukerian
2  kailash     67  gurdaspur
3  kuljeet     78      jammu

In [5]:
df.to_csv('student_marks.csv',index=False)

In [6]:
newdf = pd.DataFrame(
    np.random.rand(334, 5),
    index=range(334)
)

In [7]:
newdf

            0         1         2         3         4
0    0.291620  0.268257  0.868588  0.209545  0.655518
1    0.283528  0.399442  0.873009  0.803281  0.039216
2    0.580530  0.941029  0.006901  0.698203  0.224997
3    0.409934  0.609616  0.637138  0.447051  0.442250
4    0.014009  0.006338  0.981189  0.820999  0.641366
..        ...       ...       ...       ...       ...
329  0.351792  0.498760  0.051359  0.628666  0.383387
330  0.178017  0.086225  0.374037  0.161714  0.854479
331  0.349428  0.977088  0.560447  0.467621  0.177011
332  0.446602  0.023702  0.960135  0.455376  0.569022
333  0.818359  0.351780  0.339967  0.872056  0.628722

[334 rows x 5 columns]

In [8]:
import numpy as np
import pandas as pd
ndf= pd.DataFrame(np.random.rand(500,54),index=range(500))

In [9]:
ndf

,0,1,2,3,4,5,6,7,8,9,...,44,45,46,47,48,49,50,51,52,53
0,0.563878,0.490873,0.897937,0.216609,0.625892,0.868197,0.125298,0.681118,0.798661,0.508409,...,0.624011,0.363854,0.088317,0.928644,0.681730,0.897467,0.731343,0.913701,0.196122,0.135093
1,0.690242,0.572566,0.920247,0.514253,0.838053,0.901016,0.609236,0.873235,0.549245,0.718162,...,0.106822,0.845552,0.805591,0.760078,0.156823,0.168304,0.256664,0.669032,0.429354,0.191870
2,0.387065,0.647050,0.778693,0.195621,0.480258,0.606883,0.830050,0.255811,0.666997,0.443505,...,0.273899,0.983664,0.836498,0.930594,0.478926,0.585258,0.387729,0.434911,0.272755,0.112809
3,0.383508,0.677781,0.257805,0.537105,0.543823,0.864880,0.769937,0.772704,0.368051,0.306254,...,0.721262,0.097804,0.282075,0.229859,0.102290,0.920620,0.523840,0.475518,0.816845,0.250604
4,0.544530,0.165339,0.034092,0.763832,0.470481,0.978218,0.427532,0.086221,0.989352,0.914149,...,0.568626,0.860660,0.855728,0.163964,0.106073,0.073443,0.748709,0.563822,0.448824,0.560546
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,0.450524,0.723207,0.114686,0.046250,0.970804,0.895064,0.260336,0.044976,0.849238,0.432840,...,0.669595,0.459705,0.091185,0.959037,0.992437,0.618915,0.045892,0.526657,0.466087,0.768806
496,0.464388,0.952418,0.295868,0.647158,0.816133,0.361739,0.938898,0.312070,0.223342,0.940741,...,0.438236,0.010188,0.597248,0.716406,0.978293,0.298818,0.255781,0.134412,0.113476,0.208067
497,0.085089,0.986533,0.667598,0.961374,0.292604,0.766087,0.515635,0.537853,0.520692,0.428986,...,0.771891,0.876399,0.934318,0.510488,0.129968,0.582526,0.567974,0.823210,0.171186,0.064275
498,0.161703,0.146615,0.893138,0.441669,0.311939,0.633791,0.568838,0.620408,0.088007,0.638025,...,0.896078,0.614192,0.657893,0.379206,0.707525,0.686602,0.752142,0.787734,0.684947,0.499810
499,0.996078,0.247226,0.623773,0.618970,0.456679,0.871887,0.962017,0.117758,0.378868,0.770313,...,0.122051,0.847485,0.147732,0.178135,0.865257,0.030409,0.652890,0.230689,0.585515,0.969973

In [20]:
print(ndf.index)

RangeIndex(start=0, stop=500, step=1)

In [22]:
ndf.columns

RangeIndex(start=0, stop=54, step=1)

In [23]:
ndf.index

RangeIndex(start=0, stop=500, step=1)